version: '3'
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    restart: always
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    restart: always

