version: '3'
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    restart: always
    ports:
      - 9090:9090
    extra_hosts:
      - "host.docker.internal:host-gateway"
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    restart: always
  curl:
    image: curlimages/curl
    command: tail -f /dev/null
    extra_hosts:
      - "host.docker.internal:host-gateway"
